if(EXISTS "${PLABUNDLE_PUBLIC_INCLUDE_DIR}/camera.h")
    message(FATAL_ERROR "PlaBundle must not install plabundle/camera.h")
endif()
if(EXISTS "${PLABUNDLE_PUBLIC_INCLUDE_DIR}/rig.h")
    message(FATAL_ERROR "PlaBundle must not install plabundle/rig.h")
endif()
file(GLOB public_headers "${PLABUNDLE_PUBLIC_INCLUDE_DIR}/*.h")
foreach(header IN LISTS public_headers)
    file(READ "${header}" contents)
    if(contents MATCHES "plabundle::FrameCamera|struct[ \t]+FrameCamera|struct[ \t]+RigTopology")
        message(FATAL_ERROR "deleted PlaBundle camera/rig type leaked into ${header}")
    endif()
endforeach()
